#!/bin/sh

source ./venv
#[[[cog
#   import cog
#   cog.outl('workon . || mkvirtualenv {}'.format(service_name))
#]]]
#[[[end]]]
pip install -r requirements.txt
deactivate

git rev-parse HEAD > .last_prep
