#!/bin/sh

source ./venv
#[[[cog
#   import cog
#   cog.outl('workon . || mkvirtualenv {}'.format(service_name))
#]]]
#[[[end]]]
pip install -e .
pip install -e ~/work/repos/services/egor/
deactivate

git rev-parse HEAD > .last_prep
