#!/bin/sh
#[[[cog
#   import cog
#   import json
#   config = json.load('scaffold.json')
#   cog.outl('pushd {}'.format(config.name))
#   cog.outl('nameko run {}'.format(config.name))
#]]]
#[[[end]]]
popd
