#!/bin/sh
#[[[cog
#   import cog
#   import json
#   with open('scaffold.json', 'r') as f:
#       config = json.load(f)
#   cog.outl('pushd {}'.format(config['name']))
#   cog.outl('nameko run {}'.format(config['name']))
#]]]
#[[[end]]]
popd
